- name: Install packages ,docker and run containers via Ansible
  hosts: linux_server
  tasks:
    - name: Update system to latest
      apt: upgrade=dist force_apt_get=yes # apt update & apt upgrade

    - name: Install apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true
  
- name: Create user for Docker work
  hosts: linux_server
  tasks:
    - name: Create simple user and to the group
      ansible.builtin.user:
        name: zeynal
        groups: adm,docker
- name: Copy Docker-compose file ,Login to DockerHub and pull Java Application
  hosts: linux_server
  become: yes
  become_user: zeynal
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose to remote Ubuntu Host
      ansible.builtin.copy:
        src: /Users/zhajili/Desktop/DevOps/Ansible/docker-compose_mysql.yaml
        dest: /home/zeynal/docker-compose.yml
    - name: Login to DockerHub
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: zhajili
        password: "{{docker_password}}"
    - name: Start container from compose
      community.docker.docker_compose: 
        project_src: /home/zeynal

        
