---
- name: Install node and NPM
  hosts: webserver
  tasks:
    - name: update apt repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Create Linux user per Application
  hosts: webserver
  tasks:
    - name: Create Linux user
      user:
        name: user_nodejs
        comment: User NodeJs
        group: admin

- name: Deploy NodeJs Application
  hosts: webserver
  become: True
  become_user: user_nodejs
  tasks:
    - name: Unpack the nodejs file and copy to the Digital Ocean instance
      unarchive: # this command will do both ,unarchieve and copy to remote
        src: /Users/zhajili/Desktop/DevOps/Ansible/node-app-master/node-app-master.tar.gz
        dest: /home/user_nodejs
    - name: Install Dependencies
      npm:
        path: /home/user_nodejs/node-app-master
    - name: Start the Application
      command:
        chdir: /home/user_nodejs/node-app-master/app
        cmd: node server
      async: 1000
      poll: 0
    - name : Ensure App is running
      shell: ps aux | grep node # better for shell injection
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
  

      